name: '.NET Library CodeQL'
description: 'A Composite Action that runs CodeQL to Analyze a .NET 8 Library'
author: 'RICADO'
branding:
  icon: 'link'
  color: 'blue'

# Inputs
inputs:
  private-nuget-url:
    description: 'The URL of the Private NuGet Repository (e.g. https://nuget.pkg.github.com/myname/index.json)'
    required: true
  private-nuget-token:
    description: 'The Token used for Authentication with the Private NuGet Repository'
    required: true

runs:
  using: 'composite'
  steps:
    # Step 1 - Initialize CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: csharp
        queries: security-and-quality
    
    # Step 2 - Setup .NET 8 with GitHub Packages Authentication
    - name: Setup .NET 8 with GitHub Packages Authentication
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
        source-url: ${{ inputs.private-nuget-url }}
      env:
        NUGET_AUTH_TOKEN: ${{ inputs.private-nuget-token }}
    
    # Step 3 - Build the Library
    - name: Run CodeQL Autobuild
      uses: github/codeql-action/autobuild@v2
    
    # Step 4 - Perform CodeQL Analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
